version: "3"
services:

  prometheus:
    image: quay.io/prometheus/prometheus
    container_name: prometheus
    volumes:
      - "./prometheus:/etc/prometheus/"
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  node_exporter:
    image: quay.io/prometheus/node-exporter 
    container_name: node_exporter
    user: root
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports: 
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ${PWD}/grafana/grafana.ini:/etc/grafana/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter:0.3.0
    ports:
      - "9113:9113"
    environment:
      - SCRAPE_URI=http://134.209.86.63:8080/stub_status
    # command:
    #   - -nginx.scrape-uri http://134.209.86.63:8080/stub_status

volumes:
  prometheus_data:
  grafana_data:

# networks:
#   default:
#     external:
#       name: lb-net