{
 "title": "LB",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Nginx RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_connections_accepted[1s]))"
    }
   ]
  },
  {
   "title": "RPS-1",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(backend1_hits_by_http_status{job=\"backend1\"}[1s]))"
    }
   ]
  },
  {
   "title": "RPS-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(backend1_hits_by_http_status{job=\"backend2\"}[1s]))"
    }
   ]
  },
  {
   "title": "RPS-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(backend1_hits_by_http_status{job=\"backend3\"}[1s]))"
    }
   ]
  },
  {
   "title": "LA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"prometheus\"}"
    },
    {
     "expr": "node_load5{job=\"prometheus\"}"
    },
    {
     "expr": "node_load15{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "LA-1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"backend1\"}"
    },
    {
     "expr": "node_load5{job=\"backend1\"}"
    },
    {
     "expr": "node_load15{job=\"backend1\"}"
    }
   ]
  },
  {
   "title": "LA-2",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"backend2\"}"
    },
    {
     "expr": "node_load5{job=\"backend2\"}"
    },
    {
     "expr": "node_load15{job=\"backend2\"}"
    }
   ]
  },
  {
   "title": "LA-3",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"backend3\"}"
    },
    {
     "expr": "node_load5{job=\"backend3\"}"
    },
    {
     "expr": "node_load15{job=\"backend3\"}"
    }
   ]
  }
 ]
}